### ISSUE TITLE
Timezone error

### ISSUE THREAD

**Issue by dqunbp** [yunojuno/django-request-token#11]
Why do I get an error when running the test on my local machine?
Travis build passes successfully.

`
ERROR: test_jwt (request_token.tests.test_models.RequestTokenTests)
Traceback (most recent call last):
  File "C:\Users\2\Documents\django-proj\temp\django-request-token\request_token\tests\test_models.py", line 226, in test_jwt
...
InvalidIssuedAtError: Issued At claim (iat) cannot be in the future.
`

When i replace tz_now -> utcnow in code, tests are successful

**Comment by hugorodgerbrown** [comment]
@dqunbp do you have any more details - were you running the tests through tox, or directly, and were there any specific configurations (python 2/3, django 1.x) that were failing.

Also - what is the local machine locale set to?

**Comment by hugorodgerbrown** [comment]
@dqunbp am going to close this issue if no further information available.

**Comment by dqunbp** [comment]
Sorry for long time answer, soon i send information

**Comment by hugorodgerbrown** [comment]
That would be great - if you could include steps to reproduce the problem.
