### ISSUE TITLE
Make compatible with custom user models

### ISSUE THREAD

**Issue by tjwalch** [yunojuno/django-request-token#12]
If the `RequestToken.user` and `RequestTokenLog.user` fields have `to=settings.AUTH_USER_MODEL` this app can be used in projects with custom user models as well. (As descripbed by the [Django docs](https://docs.djangoproject.com/en/1.11/topics/auth/customizing/#referencing-the-user-model))

Otherwise nice work!

**Comment by hugorodgerbrown** [comment]
Happy to take a PR for this ;-)

**Comment by dqunbp** [comment]
I already had this problem, and I fixed it for myself

**Comment by hugorodgerbrown** [comment]
There are some py36 cleanup issues that I need to do before the next release - will probably be tomorrow.

**Comment by hugorodgerbrown** [comment]
Pushed as v0.6
