### ISSUE TITLE
LOGIN_MODE_SESSION does not support user with UUID primary key

### ISSUE THREAD

**Issue by alo-is** [yunojuno/django-request-token#18]
Hi, 

It seems that when user model is custom and uses an UUID as primary key, things goes wrong when serializing the object, with a classic `UUID('xxxxx-xxxxx-xxxxx-xxxxx-xxxxxxxxx') is not JSON serializable` error.

Fixing it just requires to check if `user.id` type is `uuid` or not, and cast with `str()` the value.

Thanks for help in solving this (little) issue !

**Comment by timomeara** [comment]
if you also want to support custom user models (and why wouldn't you?)
i think all you need to do is:
claims["aud"] = str(self.user.pk)
that's working for me anyway...

**Comment by hugorodgerbrown** [comment]
Hi @timomeara - thanks for the comment. I would strongly recommend moving to `django-magic-link` if you are still using the session mode - it's a cleaner implementation that came out of this library, and `LOGIN_MODE_SESSION` is due for deprecation.

**Comment by timomeara** [comment]
hey @hugorodgerbrown 
i'm not using LOGIN_MODE_SESSION but i am using the django-request-token a little differently.

i'm building a rest api for a mobile app so i'm not using the middleware. my endpoints expect the tokens in post data.
i decode the token and retrieve the RequestToken object manually using values from the claim

regardless, the problem arises when building the claims for the token.

if there's a user it'll try to set the claims AUD value to user.id (LOGIN_MODE_REQUEST would do that too) 

all i'm saying in that the safe, compatible way to do that would be: str(user.pk)

that'll support uuid's as well as custom models where the pk field is called something other than 'id'
 
here's a PR for the changes
[https://github.com/yunojuno/django-request-token/pull/52](https://github.com/yunojuno/django-request-token/pull/52)

**Comment by hugorodgerbrown** [comment]
@timomeara this is now out as v0.15. thanks for the submission.
