### ISSUE TITLE
Cutting a new releaes for PyPi

### ISSUE THREAD

**Issue by Xorso** [yunojuno/django-request-token#21]
I am looking to use this package with a project that I am working on as it satisifies nearly all of my requirements. But I ran into an issue where the current master has the changes I need to work with Django 2.0. But it looks like there hasn't been a release cut to PyPi with the changes.

Can a new version be released with the most recent changes?

**Comment by hugorodgerbrown** [comment]
Latest version on PyPI (0.8) supports Django 2.0
