### ISSUE TITLE
Version 0.2.0 & 0.2.1 fails on my side

### ISSUE THREAD

**Issue by pmarais** [yunojuno/django-request-token#4]
I have installed the new versions with support for 403 page and the 403 page works, the token-authorisation fails.

Have you found any similar issues?

I am a bit snowed under right now but I can help you debug if needed. For now though, the versions>0.2 are not working from a pip install on my end.

**Comment by hugorodgerbrown** [comment]
I've updated the tests - they weren't actually testing the 403 branch - however no errors appeared, and I've just tested running it locally and it seems fine. The /testing/decorated/ URL works, and logs a `RequestTokenLog` as expected. Do you have any more details?

**Comment by hugorodgerbrown** [comment]
I've also added a hard check on app config now so that if a 403 template is specified, but cannot be loaded, it will bomb out with an `ImproperlyConfigured` exception.

**Comment by hugorodgerbrown** [comment]
@pmarais is this still an issue, or can I close it?
