### ISSUE TITLE
Migration don't work with mariaDB backend

### ISSUE THREAD

**Issue by Bonten156** [yunojuno/django-request-token#47]
Hi, 
I tried to use your library but I have some errors when I migrate request_token.0008_convert_token_data_to_jsonfield:

``` 
MySQLdb._exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json
b NOT NULL' at line 1")
```

Your library seems to be good, I hope I can use it !

Edit: 
related to #22

**Comment by hugorodgerbrown** [comment]
Hi there. The library works with the Django JSONField. It will support Postgres with Django 2.2/3.0, and it _should_ support MariaDB from 3.1 (https://docs.djangoproject.com/en/3.1/ref/models/fields/#django.db.models.JSONField)

Support for JSON fields within specific database backends is outside of the scope of this library.
